# Generated by Django 4.2.7 on 2023-11-24 17:53

from django.db import migrations, models
import django.db.models.deletion
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_blogmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(upload_to=services.uploader.Uploader.upload_photo_to_blog)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.blogmodel')),
            ],
            options={
                'verbose_name': 'blog sekili',
                'verbose_name_plural': 'blog sekilleri',
                'ordering': ('-created_at',),
            },
        ),
    ]
