# Generated by Django 4.2.7 on 2023-11-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='tag adi')),
            ],
            options={
                'verbose_name': 'hastag',
                'verbose_name_plural': 'hastaglar',
                'ordering': ('created_at',),
            },
        ),
    ]
