# Generated by Django 4.2.7 on 2023-11-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='hastags',
            field=models.ManyToManyField(to='my_app.hashtag'),
        ),
    ]
