# Generated by Django 4.2.7 on 2023-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_blogmodel_hastags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='reading_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='oxuma sayi'),
        ),
    ]
